### ISSUE TITLE
Issues Desmos Airdrop

### ISSUE THREAD

**Issue by AlpinePress** [g-luca/go-find#13]
Greetings,
This is my 1st time on GitHub, please forgive my difficulty in navigating tech, I'm a 55yr old carpenter trying to figure this out. Lol
I use a Macbook Pro and created a Desmos profile on Nov. 18. My Nickname is @BretSmith831 and my Dtag is @AlpinePress66.
I've had no luck claiming my DSM airdrop. I can see that I will receive 451 DSM when I eventually figure this out.
I added Desmos to my Keplr Wallet extension (all good)
I went to go-find.me, I have attempted both pathways (Get Started) and (Use Keplr) to no avail.
When I use my Dtag and Password and I click on Continue, nothing happens.
When I use Keplr Wallet it doesn't recognize my Dtag.
When I am on my Forbole X Wallet and I click on DSM Airdrop banner at the top of screen, it eventually leads me to needing to use my seed phrase (which everyone recommends I don't do) in order to connect my Desmos Profile to my wallet accounts.
I do have 0.09 DSM in my account.
I'm flummoxed and could use some help.
Thanks,
Bret Smith

**Comment by g-luca** [comment]
In order to claim the airdrop if you don't want to input the seed of the external wallets you have 2 choices:
1. ForboleX if you have a Ledger
2. Go-find.me if you want to use Keplr.

If you use go-find is important that you create a Keplr account using the same seed of the external address that you want to connect (ex. if you need to claim an Osmosis airdrop you need to create a Keplr account with the same seed of osmosis).
Then you just have to click "Connect a Blockchain" and choose the eligible chain.
Once claimed, you can always transfer the airdropped DSM to another desmos address using the Keplr send.

**Comment by AlpinePress** [comment]
Thanks for replying.
I guess I don't understand why with an existing Keplr account, and an existing Desmos profile (set up before airdrop) I'm unable to claim ?
It won't recognize my Dtag  when I attempt to claim via Keplr with go-find.me
I also use a Mac which seems problematic on their end.
Their Discord offers a lot of general advice, but none of their advice has worked specifically for my situation.
I already created a Desmos profile before the airdrop. I have an established Dtag and an established Keplr wallet.
I don't want to input any seed phrase(s).
Do I need to start a new profile as a way to bypass the requirement to input my seed phrase ?
I'm a carpenter, so please explain like you would explain to a 5yr old... Lol
