### ISSUE TITLE
Can't Log IN

### ISSUE THREAD

**Issue by shanealthor** [g-luca/go-find#18]
After I set up an account, connected chains, claimed Desmos airdrop, I logged out and now can't log back in.

**Comment by g-luca** [comment]
Hi, Did you use Keplr or the standard signin by password?

If you used Keplr please check that you selected the right account:
1. open the keplr extension
2. click the profile icon on the top right corner
3. select the right profile, and try to login again with Keplr

Otherwise, you can follow the password recovery process:
1. open https://go-find.me/register
2. If you saved the profile on chain, click "Already have a Desmos Profile". (verify if you saved on chain here: https://explorer.desmos.network/accounts/{desmosaddress} )
3. Import your seed
