### ISSUE TITLE
DSMAirDrop

### ISSUE THREAD

**Issue by tekuteku76** [g-luca/go-find#20]
Hello.

I created an account at Go-find.me and tried to request a DSM airdrop.
When I connect the blockchain to my account and click on the Airdrop button, it shows me the quantities I can claim, but when I click on the Claim button, I get the message "There are no claimable airdrops left to be claimed. Why does this happen?
Cosmos, Osmosis, Sifchain, and Desmos are now connected.

I tried to log out and try again, but now I can't log in.

**Comment by g-luca** [comment]
Hi, probably something went wrong when saving the profile on chain, you can verify if your profile is correctly saved on chain here: https://explorer.desmos.network/accounts/{desmosaddress}

Then, did you use Keplr or the standard signin by password?

If you used Keplr please check if you selected the right account:
1. open the keplr extension
2. click the profile icon on the top right corner
3. select the right profile, and try to login again with Keplr

Otherwise, you can follow the password recovery process:
1. open https://go-find.me/register
2. If you saved the profile on chain, click "Already have a Desmos Profile". 
3. Import your seed

**Comment by saendu** [comment]
For anybody that ends up here: I had the same issue as described above. Reason was that I already created a desmos wallet (Apple Store App) with the same dtag and then tried to create a go-finde.me account with the same dtag name. 

How I fixed it: 
1. Open desmos app on iphone
2. edit profile and change dtag and nickname
3. go back to go-find.me and repeat the process.

Now there shouldn't be any error since there is no dtag name confusion. Hope this makes sense.
