### ISSUE TITLE
Airdrop Keplr 

### ISSUE THREAD

**Issue by markosmak** [g-luca/go-find#32]
hi i claimed my desmos airdrop with an account not connected to my keplr wallet but added my cosmo address to that account. i have now managed to connect that cosmo account to a new keplr wallet but am unable to claim my airdrop because of what i have done. what can i do to fix it? thank you

**Comment by markosmak** [comment]
it says grant has already been requested my desmos...(wallet)

**Comment by g-luca** [comment]
If you requested the grant to the wrong desmos account you have 2 options:
1. login to your first desmos address and send your granted DSM to the new desmos address
2. [Join Discord](https://discord.gg/ckFcU5vxxc) and ask in the chat or dm me (Luca | GStake), i'll send you some DSM in order to do the airdrop
