### ISSUE TITLE
Go-find.me login issue

### ISSUE THREAD

**Issue by RodrigoSantos19** [g-luca/go-find#48]
I created a profile in go-find.me website and after depositing dsm tokens in the address there presented, I encountered problems on staking those same dsm tokens. Error messages kept showing without allowing for the staking to procede as intended. Upon these problems I tried to log off and log back in without success. Now I have my dsm tokens there and can´t access them. Please help me solve this issue. Thanks

p.s. my dtag is @RodrigoSantos19

**Comment by g-luca** [comment]
Hi, i i've done some checks, and everything looks good to me in your account credentials, when logging in pay attention to input `RodrigoSantos19` instead of `@RodrigoSantos19`.

Anyway if still don't work or you don't remember the password, you can always do a password reset:

1. go to https://go-find.me/register
2. click "Already have a Desmos Profile", and input `RodrigoSantos19`
3. then choose your new passwords, and the old seed

Otherwise you can create a new Keplr account with that seed, and then just login with it.
If you still have problems to login, don't hesitate to reopen this issue!
