### ISSUE TITLE
DSM balance on the website doesn't reflect what is actually on chain.

### ISSUE THREAD

**Issue by umutberkbilgic** [g-luca/go-find#58]
I don't know if this is an issue with the node being used to access data but the balances for DSM are always at zero and do not reflect the actual DSM balance of that address. 

![image](https://user-images.githubusercontent.com/17654512/154990577-31ca7f71-d50e-4887-aac7-a983a4304e34.png)
![image](https://user-images.githubusercontent.com/17654512/154990611-5f8d4e99-0708-4b62-a996-342eeead7e06.png)

If node is the issue maybe have backup query nodes and run a sanity check for all node data being obtained? Yes it's a bit slower on the load but its a one time deal on page refresh.

Browser: Brave, Chrome (tried adblocker both on and off with clear caches each time)

Also tried the suggest stages of deleting the Desmos from the keplr wallet and switching to the new config.

**Comment by g-luca** [comment]
Hi, Go-find.me uses the same data sources of the [explorer](https://explorer.desmos.network) and in the last hours had several problems since the parser was missing blocks, now you should see the correct amount of DSM on your balance.

Anyway thanks for the suggestion, i'm actually working on a general refactor of the app and definitely this backup query will be implemented!
