### ISSUE TITLE
Transaction error when unbounding

### ISSUE THREAD

**Issue by lorenzomenegon** [g-luca/go-find#61]
A user reported a transaction error when unbounding via go-find.me. Specifically, this user has connected Keplr and is using the Google Chrome version 105. Below is the error log. Sorry for the low quality but it's the only image I was able to get. Please, let me know if there is a possible solution.

![2022-09-09 11 52 52](https://user-images.githubusercontent.com/106406454/189324742-10a65e77-19d5-473e-9659-7a694abdc1f3.jpg)

**Comment by g-luca** [comment]
Does this happen only with the unbonding transaction or also with any other?
From the error log it looks like the user is trying to make a transaction with the wrong Keplr account, may have switched Keplr account and go-find.me din't detect it correctly. 

Can you check if the desmos address displayed on go-find matches the Desmos Keplr account address?
If it doesn't, just log out and log back in or switch to the correct Keplr account, then it should work correctly.

**Comment by lorenzomenegon** [comment]
Apparently the address of Keplr and the address of go-find.me did not coincide and the user logged out, but the new login with Keplr marks 0 dsm, as probably these were on the address (_generated?_ the user ensures that he has logged in via Keplr and has only one account, but at that point the addresses should have coincided) on go-find.me. At this point the user is trying to log back into his account with the dsm inside, but apparently he is unable to log in via this screen.
Any suggestions? (he tried to add the @ before the dtag too and claims to have never created a new wallet and received the mnemonic)
![2022-09-14 12 36 23](https://user-images.githubusercontent.com/106406454/190132294-08c15be9-083a-4899-a326-097ecca02cb2.jpg)

**Comment by g-luca** [comment]
This login method works only if the user generated a brand new mnemonic directly from go-find. If the user didn't used this signup method it won't work. In any case i also checked from the logs, and i can confirm that didn't used this method.

At this point honestly i don't have many clues either, go-find relies completely on the keplr library :
`Go-find asks for a Keplr connection -> Keplr returns the user address & publicKey`, so i can't see how an address could be generated in a bad way.
There are only 2 options here:
1. Was using a Ledger device. If so, that might be the issue since was enforcing a wrong derivation path (´118´ insted of ´852´).
2. He actually changed account or desmos configuration. In order to try to fix it just try to remove the Desmos Mainnet profile from Keplr, and then by refreshing the profile page it will prompt a new Desmos keplr configuration.
